---
abstract: 'Sealed class for Microsoft Visual Studio Database Edition UnitTest Utility Suite by Ded MedVed'
author:
  - 'Ded MedVed <dedmedved@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VSGDR-UnitTest-TestSet
no_index:
  directory:
    - t
    - inc
requires:
  Array::Diff: 0
  Carp: 0
  Clone: 0
  DBD::ODBC: 0
  DBI: 0
  Data::Dumper: 0
  English: 0
  File::Basename: 0
  Getopt::Euclid: 0
  IO::File: 0
  IPC::System::Simple: 0
  List::MoreUtils: 0
  List::Util: 0
  Modern::Perl: 0
  Parse::RecDescent: 0
  Readonly: 0
  Smart::Comments: 0
  Spreadsheet::ParseExcel: 0
  Spreadsheet::WriteExcel: 0
  Storable: 0
  Test::More: 0
  Text::Diff: 0
  Try::Tiny: 0
  XML::Quote: 0
  XML::Simple: 0
  autodie: 0
  indirect: 0
  perl: 5.010000
  version: 0
version: 1.30
